from audit import *
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
I=json.load(open(B/'inventory.json'));X=json.load(open(B/'mesh_batch.json'));allrows=[dict(episode=e['episode'],**r) for e in X for r in e['frames']];rows=[r for r in allrows if r['n_hits']>=30];dz=np.array([r['surface_depth_difference_mm']['median'] for r in rows]);xyz=np.array([r['surface_xyz_gap_mm']['median'] for r in rows]);epmed=[]
for e in X:
 valid=[r for r in e['frames'] if r['n_hits']>=30]
 epmed.append(dict(episode=e['episode'],source=I[e['episode']]['source'],valid_frames=len(valid),median_xyz_mm=float(np.median([r['surface_xyz_gap_mm']['median'] for r in valid])) if valid else None,median_signed_z_mm=float(np.median([r['surface_depth_difference_mm']['median'] for r in valid])) if valid else None))
J=json.load(open(B/'summary.json'));source=json.load(open(B/'source_checks.json'))
report=dict(status='complete',episodes=len(X),source_counts={s:sum(v['source']==s for v in I.values()) for s in ['9.24','10.1']},duplicates=0,joint_audit_frames=J['sampled_frames'],surface_sampled_frames=len(allrows),surface_accepted_frames=len(rows),surface_excluded_frames=len(allrows)-len(rows),surface_matches=sum(r['n_hits'] for r in rows),accepted_candidate_rays=sum(r['n_rays'] for r in rows),all_candidate_rays=sum(r['n_rays'] for r in allrows),frame_median_surface_xyz_mm=stats(xyz),frame_median_signed_surface_z_mm=stats(dz),positive_depth_frames=int((dz>0).sum()),negative_depth_frames=int((dz<0).sum()),urdf=str(URDF),urdf_sha256=hashlib.sha256(URDF.read_bytes()).hexdigest(),camera_R=R.tolist(),camera_t=t.tolist(),fk_recompute_max_frame_p95_mm=max(r['fk_link_origin_nearest_mm']['p95'] for r in allrows),all_cache_frame_counts_match=all(r['cache_frames_match'] for r in source),all_export_and_evaluation_videos_identical=all(r['video_identical'] for r in source),sensor_checks=json.load(open(B/'sensor_check.json')),aggregation='Statistics over per-frame medians, not pooled point quantiles; frames require >=30 mesh intersections.',methods=['Existing 9.24/10.1 v61 data merged; no GPU rerun or geometry correction.','Recorded qpos + provided DAgger URDF visual meshes, fixed camera chain and 180deg optical roll.','Calibrated per-episode head colour intrinsics, resized to 640x448; no fitted extrinsic, scale or translation.','Valid & unique class2 points, 5x5 mask erosion, every fourth pixel on each image axis; nearest hand surface ray hit at the same pixel.','FK recomputed from qpos checked against supplied mix_fk21 landmark positions.'],limitations=['URDF/glove shape and residual camera calibration errors remain; mesh is not perfect physical ground truth.','v61 masks may include arms/cables; only hand mesh intersections measured, unmatched regions excluded.','Object occlusion is not independently rendered; retained mask provides a visibility approximation.','D435 corroboration covers four frames only; nearest depth frames differ by -1 to +2 video indices, sensor noise and latency remain.','Changing error sign does not establish random noise; repeat-inference variance has not been measured.'])
(B/'final_report.json').write_text(json.dumps(report,indent=2));(B/'episode_surface_summary.json').write_text(json.dumps(epmed,indent=2))
fig,axs=plt.subplots(2,2,figsize=(14,9),constrained_layout=True)
axs[0,0].hist(dz/10,bins=40,color='#e67e22');axs[0,0].axvline(0,color='k');axs[0,0].set(xlabel='Per-frame median PF Z - FK surface Z (cm)',ylabel='Frames',title=f'Signed depth: median {np.median(dz)/10:+.1f} cm; both signs present')
axs[0,1].hist(xyz/10,bins=40,color='#1565c0');axs[0,1].set(xlabel='Per-frame median 3D surface gap (cm)',ylabel='Frames',title=f'Median {np.median(xyz)/10:.1f} cm; frame-median P95 {np.percentile(xyz,95)/10:.1f} cm')
e=[r for r in epmed if r['median_xyz_mm'] is not None];axs[1,0].plot(np.sort([r['median_xyz_mm']/10 for r in e]),'.');axs[1,0].set(xlabel='Episode rank (sorted)',ylabel='Episode median 3D gap (cm)',title='71 merged episodes, no duplicates')
for ep,label in [('episode_0002_20260830_155725','9.24 ep0002'),('episode_0005_20260903_185554','10.1 ep0005')]:
 r=[v for v in rows if v['episode']==ep];axs[1,1].plot([v['frame'] for v in r],[v['surface_depth_difference_mm']['median']/10 for v in r],'o-',label=label)
axs[1,1].axhline(0,color='gray');axs[1,1].set(xlabel='Frame',ylabel='Signed depth difference (cm)',title='Representative episodes: depth bias changes over time');axs[1,1].legend()
fig.suptitle(f'DAgger | 71 episodes | {len(rows)}/{len(allrows)} accepted sampled frames | supplied URDF, no alignment fitting',fontsize=14);fig.savefig(B/'surface_summary.png',dpi=160);plt.close(fig)
print(json.dumps({k:report[k] for k in ['episodes','surface_sampled_frames','surface_accepted_frames','surface_matches','frame_median_surface_xyz_mm','frame_median_signed_surface_z_mm']},indent=2))
